# Release helpers for The Story Nexus.
#
# Override NPM=npm if your shell resolves npm reliably. The default uses npm.cmd
# because it is the most predictable npm shim from Windows automation.

NPM ?= npm.cmd
APP_VERSION ?= $(shell powershell -NoProfile -ExecutionPolicy Bypass -Command "(Get-Content package.json | ConvertFrom-Json).version")
UPDATER_KEY ?= $(USERPROFILE)\.tauri\thestorynexus.key
UPDATER_PASSWORD_FILE ?= $(UPDATER_KEY).password
UPDATER_JSON ?= dist\updater\latest.json
UPDATER_TARGET ?= windows-x86_64
PUB_DATE ?= $(shell powershell -NoProfile -ExecutionPolicy Bypass -Command "(Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')")
RELEASE_NOTES ?=
TAURI_SIGNING_PRIVATE_KEY_PASSWORD ?=

.PHONY: help updater-info updater-key updater-build updater-json updater-files release release-dry-run

help:
	@powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Write-Host 'The Story Nexus release helpers'; Write-Host ''; Write-Host 'Targets:'; Write-Host '  make -f Makefile updater-info'; Write-Host '      Show updater helper settings.'; Write-Host '  make -f Makefile updater-key'; Write-Host '      Generate the Tauri updater signing key if it does not exist.'; Write-Host '  make -f Makefile updater-build'; Write-Host '      Build a signed Tauri release using the local updater key.'; Write-Host '  make -f Makefile updater-files'; Write-Host '      List MSI updater artifacts generated by the latest build.'; Write-Host '  make -f Makefile updater-json MSI_URL=... SIG_FILE=...'; Write-Host '      Create dist\updater\latest.json for a manual GitHub release.'; Write-Host '  make -f Makefile release VERSION=1.2.9'; Write-Host '      Build, test, tag, upload assets, and create the GitHub release.'; Write-Host '  make -f Makefile release-dry-run VERSION=1.2.9'; Write-Host '      Preview release commands and the user-facing release body.'; Write-Host ''; Write-Host 'Common overrides:'; Write-Host '  NPM=npm'; Write-Host '  UPDATER_KEY=C:\path\to\thestorynexus.key'; Write-Host '  UPDATER_PASSWORD_FILE=C:\path\to\thestorynexus.key.password'; Write-Host '  APP_VERSION=1.2.8'; Write-Host '  RELEASE_NOTES=""Short release notes""'"

updater-info:
	@powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Write-Host 'App version:           $(APP_VERSION)'; Write-Host 'Updater key:           $(UPDATER_KEY)'; Write-Host 'Updater password file: $(UPDATER_PASSWORD_FILE)'; Write-Host 'Updater JSON:          $(UPDATER_JSON)'; Write-Host 'Updater target:        $(UPDATER_TARGET)'; Write-Host 'npm command:           $(NPM)'"

updater-key:
	@powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$$ErrorActionPreference = 'Stop'; $$keyPath = '$(UPDATER_KEY)'; $$passwordFile = '$(UPDATER_PASSWORD_FILE)'; if (Test-Path -LiteralPath $$keyPath) { Write-Host \"Updater key already exists: $$keyPath\"; Write-Host 'Keeping the existing key. Do not replace it unless you are intentionally resetting updater trust.'; exit 0 }; New-Item -ItemType Directory -Force -Path (Split-Path -Parent $$keyPath) | Out-Null; $$bytes = New-Object byte[] 32; $$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create(); try { $$rng.GetBytes($$bytes) } finally { $$rng.Dispose() }; $$password = [Convert]::ToBase64String($$bytes); Set-Content -LiteralPath $$passwordFile -Value $$password -NoNewline; & '.\node_modules\.bin\tauri.cmd' signer generate --ci -w $$keyPath -p $$password; if ($$LASTEXITCODE -ne 0) { exit $$LASTEXITCODE }; Write-Host ''; Write-Host \"Private key created at: $$keyPath\"; Write-Host \"Password file created at: $$passwordFile\"; Write-Host 'Put the printed public key into src-tauri\tauri.conf.json when enabling the updater.'"

updater-build:
	@powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$$ErrorActionPreference = 'Stop'; $$keyPath = '$(UPDATER_KEY)'; $$passwordFile = '$(UPDATER_PASSWORD_FILE)'; if (-not (Test-Path -LiteralPath $$keyPath)) { throw \"Missing updater private key at '$$keyPath'. Run 'make -f Makefile updater-key' first.\" }; $$password = '$(TAURI_SIGNING_PRIVATE_KEY_PASSWORD)'; if (Test-Path -LiteralPath $$passwordFile) { $$password = (Get-Content -LiteralPath $$passwordFile -Raw).Trim() }; $$env:TAURI_SIGNING_PRIVATE_KEY = $$keyPath; $$env:TAURI_SIGNING_PRIVATE_KEY_PASSWORD = $$password; & '$(NPM)' run tauri build; if ($$LASTEXITCODE -ne 0) { exit $$LASTEXITCODE }"

updater-files:
	@powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$$ErrorActionPreference = 'Stop'; $$msiDir = 'src-tauri\target\release\bundle\msi'; if (-not (Test-Path -LiteralPath $$msiDir)) { throw \"No MSI bundle directory found at '$$msiDir'. Run 'make -f Makefile updater-build' first.\" }; Get-ChildItem -LiteralPath $$msiDir -File | Where-Object { $$_.Extension -in '.msi', '.sig' } | Sort-Object Name | Format-Table Name, Length, LastWriteTime"

updater-json:
	@powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "$$ErrorActionPreference = 'Stop'; if ([string]::IsNullOrWhiteSpace('$(MSI_URL)')) { throw 'Set MSI_URL to the final GitHub Release download URL for the MSI.' }; if ([string]::IsNullOrWhiteSpace('$(SIG_FILE)')) { throw 'Set SIG_FILE to the .sig file generated next to the MSI.' }; $$sigFile = '$(SIG_FILE)'; if (-not (Test-Path -LiteralPath $$sigFile)) { throw \"Signature file not found: $$sigFile\" }; $$signature = (Get-Content -LiteralPath $$sigFile -Raw).Trim(); $$payload = [ordered]@{ version = '$(APP_VERSION)'; notes = '$(RELEASE_NOTES)'; pub_date = '$(PUB_DATE)'; platforms = [ordered]@{ '$(UPDATER_TARGET)' = [ordered]@{ signature = $$signature; url = '$(MSI_URL)' } } }; $$jsonPath = '$(UPDATER_JSON)'; New-Item -ItemType Directory -Force -Path (Split-Path -Parent $$jsonPath) | Out-Null; $$json = $$payload | ConvertTo-Json -Depth 6; $$utf8NoBom = New-Object System.Text.UTF8Encoding -ArgumentList $$false; [System.IO.File]::WriteAllText($$jsonPath, $$json, $$utf8NoBom); $$bytes = [System.IO.File]::ReadAllBytes($$jsonPath); if ($$bytes.Length -ge 3 -and $$bytes[0] -eq 0xEF -and $$bytes[1] -eq 0xBB -and $$bytes[2] -eq 0xBF) { throw 'Updater metadata must be UTF-8 without a BOM.' }; Get-Content -LiteralPath $$jsonPath -Raw | ConvertFrom-Json | Out-Null; Write-Host \"Wrote updater metadata: $$jsonPath\"; Write-Host 'Upload this latest.json beside the MSI in the GitHub Release.'"

release:
	@powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts\create-release.ps1 -Version "$(VERSION)" -Npm "$(NPM)"

release-dry-run:
	@powershell.exe -NoProfile -ExecutionPolicy Bypass -File scripts\create-release.ps1 -Version "$(VERSION)" -Npm "$(NPM)" -DryRun -SkipVerification -AllowDirty
